# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

.PHONY: all
all:

# ##################################################################################################
# CUDA
# ##################################################################################################
CUDA ?= /usr/local/cuda

# ##################################################################################################
# TRT
# ##################################################################################################
TRT ?= /root/TensorRT-9.3.0.1/

# ##################################################################################################
# CXX.
# ##################################################################################################
CXX ?= g++

# CXX flags.
CXX_FLAGS = $(CXXFLAGS) -O3 -std=c++17 -g -fopenmp -DSAMPLES -fPIC

# ##################################################################################################
# NVCC.
# ##################################################################################################
NVCC ?= $(CUDA)/bin/nvcc

# NVCC flags.
NVCC_FLAGS := -O3 -std=c++17 --use_fast_math -DJETFIRE_ENABLED=1 -ccbin $(CXX) -Xcompiler -fPIC
# -G
# -Xptxas=-v

# ##################################################################################################
# List of includes.
# ##################################################################################################
INCLUDE_DIRS := $(CUDA)/include
INCLUDE_DIRS += $(TRT)/include

# Generate the list of -I flags for the compiler.
INCLUDE_FLAGS := $(foreach II,$(INCLUDE_DIRS),-I$(II))
