# Run unit tests with older supported Python and Torch versions
name: Multi version tests

on:
  pull_request:
    branches: [main, release/*]
    paths:
      - ".github/workflows/multi_version_unit_tests.yml"
      - "modelopt/**"
      - "tests/unit/**"
      - "setup.py"
      - "tox.ini"

# Cancel previous runs if new commit is pushed to the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  multi-py-unit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        py: [10, 11]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.${{ matrix.py }}"
      - name: Run unit tests
        run: pip install tox && tox -e py3${{ matrix.py }}-torch28-unit
  multi-torch-unit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        torch: [25, 26, 27]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run unit tests
        run: pip install tox && tox -e py312-torch${{ matrix.torch }}-unit
