name: Partial install unit tests

on:
  pull_request:
    branches: [main, release/*]
    paths:
      - ".github/workflows/partial_unit_tests.yml"
      - "modelopt/**"
      - "tests/**"
      - "setup.py"
      - "tox.ini"

# Cancel previous runs if new commit is pushed to the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  partial-unit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        test-env: [onnx, torch]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install tox
      - name: Run unit tests
        run: tox -e py312-partial-unit-${{ matrix.test-env }}
